import { Check, Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetAdminContentQueryKey, getGetSiteContentQueryKey, useGetAdminContent, useUpdateAdminContent, type SiteContent } from '@workspace/api-client-react';
import { AdminShell } from '@/components/AdminShell';
import { fallbackContent } from '@/lib/content';

type ContentTab = 'hero' | 'services' | 'work' | 'faqs' | 'insights';

export default function AdminContent() {
  const query = useGetAdminContent();
  const updateContent = useUpdateAdminContent();
  const client = useQueryClient();
  const [content, setContent] = useState<SiteContent | null>(null);
  const [tab, setTab] = useState<ContentTab>('hero');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { if (query.data && !content) setContent(query.data); }, [query.data, content]);
  const value = content ?? fallbackContent;
  const setHero = (key: keyof SiteContent['hero'], next: string) => setContent({ ...value, hero: { ...value.hero, [key]: next } });
  const save = () => { setNotice(''); setError(''); updateContent.mutate({ data: value }, { onSuccess: (saved) => { setContent(saved); client.setQueryData(getGetAdminContentQueryKey(), saved); client.setQueryData(getGetSiteContentQueryKey(), saved); setNotice('Changes published to the live site.'); }, onError: () => setError('Your changes could not be published. Please try again.') }); };
  const addService = () => setContent({ ...value, services: [...value.services, { id: `service-${Date.now()}`, title: 'New capability', description: 'Describe the transformation this capability enables.', outcome: 'A clear, measurable outcome.', tags: ['New'] }] });
  const removeService = (id: string) => setContent({ ...value, services: value.services.filter((item) => item.id !== id) });
  const addFaq = () => setContent({ ...value, faqs: [...value.faqs, { question: 'New question', answer: 'Add a considered answer.' }] });
  const removeFaq = (index: number) => setContent({ ...value, faqs: value.faqs.filter((_, i) => i !== index) });
  const input = (label: string, val: string, onChange: (next: string) => void, area = false) => <label className="block"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.15em] text-[#7d97b7]">{label}</span>{area ? <textarea data-testid={`input-content-${label.toLowerCase().replaceAll(' ', '-')}`} rows={4} value={val} onChange={(e) => onChange(e.target.value)} className="w-full resize-y rounded-lg border border-[#415c7c]/60 bg-[#0b172a] px-3 py-3 text-sm leading-6 text-[#ddecff] outline-none focus:border-[#6caffc]" /> : <input data-testid={`input-content-${label.toLowerCase().replaceAll(' ', '-')}`} value={val} onChange={(e) => onChange(e.target.value)} className="w-full rounded-lg border border-[#415c7c]/60 bg-[#0b172a] px-3 py-3 text-sm text-[#ddecff] outline-none focus:border-[#6caffc]" />}</label>;
  if (query.isLoading && !content) return <AdminShell><div className="space-y-6"><div className="skeleton h-10 w-60 rounded" /><div className="skeleton h-16 rounded-xl" /><div className="skeleton h-[500px] rounded-xl" /></div></AdminShell>;
  if (query.isError && !content) return <AdminShell><div className="rounded-xl border border-[#d86d7b]/30 bg-[#301a28] p-6 text-sm text-[#ffb6bf]">Could not load editable content. <button onClick={() => query.refetch()} data-testid="button-retry-content" className="ml-2 underline">Retry</button></div></AdminShell>;
  return <AdminShell><div className="animate-rise"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="eyebrow">Content studio</div><h1 className="mt-3 font-display text-4xl tracking-[-.055em] text-[#edf5ff]">Shape the signal.</h1><p className="mt-2 text-sm text-[#8299b5]">Edit the words that define how HXA meets the world.</p></div><div className="flex items-center gap-3">{notice && <span data-testid="status-content-success" className="flex items-center gap-1.5 text-xs text-[#72d8b7]"><Check className="h-3.5 w-3.5" />{notice}</span>}{error && <span data-testid="status-content-error" className="text-xs text-[#ff9da8]">{error}</span>}<button onClick={save} disabled={updateContent.isPending} data-testid="button-save-content" className="inline-flex items-center gap-2 rounded-full bg-[#4286f5] px-4 py-2.5 text-sm font-semibold text-[#071226] transition-colors hover:bg-[#83bdff] disabled:opacity-50"><Save className="h-4 w-4" />{updateContent.isPending ? 'Publishing…' : 'Publish changes'}</button></div></div>
    <div className="mt-10 grid gap-6 lg:grid-cols-[230px_1fr]"><nav className="flex gap-1 overflow-auto lg:flex-col">{([['hero', 'Hero & positioning'], ['services', 'Capabilities'], ['work', 'Case studies'], ['faqs', 'FAQs'], ['insights', 'Insights']] as [ContentTab, string][]).map(([key, label]) => <button key={key} onClick={() => setTab(key)} data-testid={`tab-content-${key}`} className={`whitespace-nowrap rounded-lg px-3 py-3 text-left text-sm transition-colors ${tab === key ? 'bg-[#4286f5]/15 text-[#a3d1ff]' : 'text-[#879eb9] hover:bg-[#13243d]'}`}>{label}</button>)}</nav>
      <section className="rounded-xl border border-[#405d81]/35 bg-[#0d1a2e] p-5 sm:p-8">
        {tab === 'hero' && <div className="max-w-2xl space-y-6">{input('Eyebrow', value.hero.eyebrow, (next) => setHero('eyebrow', next))}{input('Headline', value.hero.headline, (next) => setHero('headline', next))}{input('Subheadline', value.hero.subheadline, (next) => setHero('subheadline', next), true)}<div className="grid gap-5 sm:grid-cols-2">{input('Primary CTA', value.hero.primaryCta, (next) => setHero('primaryCta', next))}{input('Secondary CTA', value.hero.secondaryCta, (next) => setHero('secondaryCta', next))}</div><div className="border-t border-[#405d81]/30 pt-6">{input('Intro', value.intro, (next) => setContent({ ...value, intro: next }), true)}</div></div>}
        {tab === 'services' && <EditorList title="Capabilities" description="The three ways HXA creates measurable movement." onAdd={addService} addLabel="Add capability">{value.services.map((service, index) => <div key={service.id} className="rounded-xl border border-[#405d81]/30 bg-[#0b172a] p-5"><div className="flex items-center justify-between"><span className="font-mono text-xs text-[#73b5ff]">0{index + 1}</span><button onClick={() => removeService(service.id)} data-testid={`button-remove-service-${service.id}`} className="rounded p-2 text-[#7189a8] transition-colors hover:bg-[#632f42] hover:text-[#ffadb8]"><Trash2 className="h-4 w-4" /></button></div><div className="mt-5 grid gap-5 sm:grid-cols-2">{input('Title', service.title, (next) => setContent({ ...value, services: value.services.map((item) => item.id === service.id ? { ...item, title: next } : item) }))}{input('Outcome', service.outcome, (next) => setContent({ ...value, services: value.services.map((item) => item.id === service.id ? { ...item, outcome: next } : item) }))}</div><div className="mt-5">{input('Description', service.description, (next) => setContent({ ...value, services: value.services.map((item) => item.id === service.id ? { ...item, description: next } : item) }), true)}</div></div>)}</EditorList>}
        {tab === 'work' && <EditorList title="Case studies" description="The evidence behind the HXA point of view." onAdd={() => setContent({ ...value, caseStudies: [...value.caseStudies, { id: `case-${Date.now()}`, client: 'New client', industry: 'Industry', title: 'Case study title', result: 'Describe the transformation.', metric: 'A measurable outcome' }] })} addLabel="Add case study">{value.caseStudies.map((item) => <div key={item.id} className="grid gap-5 rounded-xl border border-[#405d81]/30 bg-[#0b172a] p-5 sm:grid-cols-2">{input('Client', item.client, (next) => setContent({ ...value, caseStudies: value.caseStudies.map((i) => i.id === item.id ? { ...i, client: next } : i) }))}{input('Industry', item.industry, (next) => setContent({ ...value, caseStudies: value.caseStudies.map((i) => i.id === item.id ? { ...i, industry: next } : i) }))}{input('Title', item.title, (next) => setContent({ ...value, caseStudies: value.caseStudies.map((i) => i.id === item.id ? { ...i, title: next } : i) }), true)}{input('Metric', item.metric, (next) => setContent({ ...value, caseStudies: value.caseStudies.map((i) => i.id === item.id ? { ...i, metric: next } : i) }))}{input('Result', item.result, (next) => setContent({ ...value, caseStudies: value.caseStudies.map((i) => i.id === item.id ? { ...i, result: next } : i) }), true)}</div>)}</EditorList>}
        {tab === 'faqs' && <EditorList title="Frequently asked questions" description="Make the first conversation easier." onAdd={addFaq} addLabel="Add question">{value.faqs.map((faq, index) => <div key={`${faq.question}-${index}`} className="rounded-xl border border-[#405d81]/30 bg-[#0b172a] p-5"><div className="flex items-start gap-4"><div className="grow space-y-5">{input('Question', faq.question, (next) => setContent({ ...value, faqs: value.faqs.map((item, i) => i === index ? { ...item, question: next } : item) }))}{input('Answer', faq.answer, (next) => setContent({ ...value, faqs: value.faqs.map((item, i) => i === index ? { ...item, answer: next } : item) }), true)}</div><button onClick={() => removeFaq(index)} data-testid={`button-remove-faq-${index}`} className="rounded p-2 text-[#7189a8] hover:bg-[#632f42] hover:text-[#ffadb8]"><Trash2 className="h-4 w-4" /></button></div></div>)}</EditorList>}
        {tab === 'insights' && <EditorList title="Insights" description="Short, useful thinking for the next move." onAdd={() => setContent({ ...value, posts: [...value.posts, { id: `post-${Date.now()}`, category: 'Point of view', title: 'New insight', excerpt: 'A short description of the idea.', readTime: '5 min read' }] })} addLabel="Add insight">{value.posts.map((post) => <div key={post.id} className="grid gap-5 rounded-xl border border-[#405d81]/30 bg-[#0b172a] p-5 sm:grid-cols-2">{input('Title', post.title, (next) => setContent({ ...value, posts: value.posts.map((i) => i.id === post.id ? { ...i, title: next } : i) }))}{input('Category', post.category, (next) => setContent({ ...value, posts: value.posts.map((i) => i.id === post.id ? { ...i, category: next } : i) }))}{input('Excerpt', post.excerpt, (next) => setContent({ ...value, posts: value.posts.map((i) => i.id === post.id ? { ...i, excerpt: next } : i) }), true)}{input('Read time', post.readTime, (next) => setContent({ ...value, posts: value.posts.map((i) => i.id === post.id ? { ...i, readTime: next } : i) }))}</div>)}</EditorList>}
      </section>
    </div>
  </div></AdminShell>;
}

function EditorList({ title, description, children, onAdd, addLabel }: { title: string; description: string; children: ReactNode; onAdd: () => void; addLabel: string }) {
  return <div><div className="mb-7 flex items-start justify-between gap-5"><div><h2 className="font-display text-2xl tracking-[-.04em] text-[#e6f1ff]">{title}</h2><p className="mt-2 text-sm text-[#8198b4]">{description}</p></div><button onClick={onAdd} data-testid={`button-add-${title.toLowerCase().replaceAll(' ', '-')}`} className="inline-flex shrink-0 items-center gap-2 rounded-full border border-[#5a83b1]/55 px-3 py-2 text-xs text-[#a6cbef] transition-colors hover:border-[#8dc6ff] hover:bg-[#4286f5]/10"><Plus className="h-3.5 w-3.5" />{addLabel}</button></div><div className="space-y-4">{children}</div></div>;
}