import { ArrowRight, FileText, FolderKanban, Inbox, RefreshCw, Server } from 'lucide-react';
import { Link } from 'wouter';
import { useGetAdminOverview } from '@workspace/api-client-react';
import { AdminShell } from '@/components/AdminShell';
import { fallbackContent } from '@/lib/content';

function AdminSkeleton() {
  return <div className="space-y-8"><div className="skeleton h-10 w-72 rounded" /><div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map((i) => <div className="skeleton h-32 rounded-xl" key={i} />)}</div><div className="skeleton h-80 rounded-xl" /></div>;
}

export default function Admin() {
  const query = useGetAdminOverview();
  const data = query.data;
  if (query.isLoading && !data) return <AdminShell><AdminSkeleton /></AdminShell>;
  if (query.isError) return <AdminShell><div className="flex min-h-[60vh] flex-col items-center justify-center text-center"><div className="grid h-14 w-14 place-items-center rounded-full bg-[#d86d7b]/10 text-[#ff9da8]"><Server /></div><h1 className="mt-5 font-display text-2xl">Could not load the workspace</h1><p className="mt-2 text-sm text-[#849bb6]">The admin API may be unavailable right now.</p><button onClick={() => query.refetch()} data-testid="button-retry-overview" className="mt-6 inline-flex items-center gap-2 rounded-full border border-[#5d82ad] px-4 py-2 text-sm text-[#a7cbef]"><RefreshCw className="h-4 w-4" />Retry</button></div></AdminShell>;
  const overview = data ?? { contentSections: 10, serviceCount: fallbackContent.services.length, caseStudyCount: fallbackContent.caseStudies.length, inquiryCount: 0, latestInquiries: [] };
  const cards = [{ label: 'Content sections', value: overview.contentSections, icon: FileText, tone: 'text-[#83c2ff]' }, { label: 'Services', value: overview.serviceCount, icon: FolderKanban, tone: 'text-[#89dfc5]' }, { label: 'Case studies', value: overview.caseStudyCount, icon: FolderKanban, tone: 'text-[#d0a7ff]' }, { label: 'Inquiries', value: overview.inquiryCount, icon: Inbox, tone: 'text-[#ffce82]' }];
  return <AdminShell><div className="animate-rise"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="eyebrow">Overview</div><h1 className="mt-3 font-display text-4xl tracking-[-.055em] text-[#edf5ff]">Good morning, Alex.</h1><p className="mt-2 text-sm text-[#8299b5]">Here is the pulse of your transformation command center.</p></div><Link href="/admin/content" data-testid="button-edit-content" className="inline-flex items-center gap-2 self-start rounded-full bg-[#4286f5] px-4 py-2.5 text-sm font-semibold text-[#071226] transition-colors hover:bg-[#83bdff]">Edit site content <ArrowRight className="h-4 w-4" /></Link></div>
    <div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <div key={label} data-testid={`metric-${label.toLowerCase().replace(' ', '-')}`} className="rounded-xl border border-[#405d81]/35 bg-[#0d1a2e] p-5"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[.14em] text-[#7189a8]">{label}</span><Icon className={`h-4 w-4 ${tone}`} /></div><div className="mt-7 font-display text-4xl tracking-[-.06em] text-[#e5f1ff]">{value}</div><div className="mt-2 text-xs text-[#6983a1]">Live from the content API</div></div>)}</div>
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="rounded-xl border border-[#405d81]/35 bg-[#0d1a2e]"><div className="flex items-center justify-between border-b border-[#405d81]/30 px-5 py-5"><div><h2 className="font-display text-xl text-[#e3effd]">Latest inquiries</h2><p className="mt-1 text-xs text-[#7289a5]">The conversations waiting for a response.</p></div><Inbox className="h-5 w-5 text-[#7ebaff]" /></div>{overview.latestInquiries.length === 0 ? <div className="flex min-h-56 flex-col items-center justify-center px-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#4286f5]/10 text-[#78b7ff]"><Inbox className="h-5 w-5" /></div><p className="mt-4 text-sm text-[#b1c6dd]">No inquiries yet.</p><p className="mt-1 text-xs text-[#7187a4]">New conversations will appear here.</p></div> : <div className="divide-y divide-[#405d81]/25">{overview.latestInquiries.map((inquiry) => <div key={inquiry.id} data-testid={`row-inquiry-${inquiry.id}`} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-[#dbeaff]">{inquiry.name} <span className="font-normal text-[#7189a5]">from {inquiry.company}</span></div><div className="mt-1 text-xs text-[#7892b0]">{inquiry.service} · {new Date(inquiry.createdAt).toLocaleDateString()}</div></div><span className="self-start rounded-full border border-[#7087aa]/35 px-2.5 py-1 text-[10px] uppercase tracking-[.13em] text-[#98b5d4]">{inquiry.status}</span></div>)}</div>}</section>
      <section className="rounded-xl border border-[#405d81]/35 bg-[#0d1a2e] p-5"><div className="eyebrow">System status</div><h2 className="mt-3 font-display text-xl text-[#e3effd]">Everything in sync.</h2><div className="mt-8 space-y-4">{['Published site', 'Content API', 'Contact intake'].map((item) => <div key={item} className="flex items-center justify-between border-b border-[#405d81]/25 pb-4 text-sm"><span className="text-[#9cb1c9]">{item}</span><span className="flex items-center gap-2 text-xs text-[#71d8b7]"><span className="h-1.5 w-1.5 rounded-full bg-[#71d8b7]" />Operational</span></div>)}</div><Link href="/admin/content" data-testid="link-dashboard-content" className="mt-8 flex items-center gap-2 text-sm text-[#82bcff]">Manage content <ArrowRight className="h-4 w-4" /></Link></section></div>
  </div></AdminShell>;
}