import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, Clock3, ExternalLink, Layers3, Mail, MoveUpRight, Orbit, Send, ShieldCheck, Zap } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { getGetSiteContentQueryKey, useCreateContactRequest, useGetSiteContent } from '@workspace/api-client-react';
import { fallbackContent } from '@/lib/content';
import SiteSkeleton from './SiteSkeleton';
import { PublicNav } from '@/components/PublicNav';

function OrbitalVisual() {
  return <div className="relative mx-auto aspect-square w-full max-w-[580px]">
    <div className="absolute inset-[9%] rounded-full border border-[#4c81c8]/30" />
    <div className="absolute inset-[20%] rounded-full border border-dashed border-[#5b98e9]/35 animate-pulse-ring" />
    <div className="absolute inset-[32%] rounded-full border border-[#78bfff]/45" />
    <div className="absolute inset-[14%] rotate-[27deg] rounded-full border border-[#4286f5]/30" />
    <div className="absolute inset-[23%] -rotate-[53deg] rounded-full border border-[#4286f5]/30" />
    <div className="absolute left-[8%] top-[33%] h-2 w-2 rounded-full bg-[#91c8ff] shadow-[0_0_18px_5px_rgba(66,134,245,.7)]" />
    <div className="absolute right-[14%] top-[19%] h-3 w-3 rounded-full bg-[#60c5ff] shadow-[0_0_24px_7px_rgba(66,134,245,.55)]" />
    <div className="absolute bottom-[21%] right-[19%] h-2 w-2 rounded-full bg-[#d4ebff] shadow-[0_0_20px_6px_rgba(107,188,255,.65)]" />
    <div className="absolute inset-[34%] grid place-items-center rounded-full bg-[#4286f5]/15 shadow-[0_0_110px_22px_rgba(47,115,220,.27)] backdrop-blur-sm">
      <div className="grid h-24 w-24 place-items-center rounded-full border border-[#a1d4ff]/65 bg-[#3175dd]/25 shadow-[inset_0_0_24px_rgba(157,212,255,.2),0_0_60px_rgba(66,134,245,.35)] sm:h-32 sm:w-32">
        <span className="font-display text-4xl font-semibold tracking-[-.1em] text-[#e6f3ff] sm:text-5xl">ADX</span>
      </div>
    </div>
    <div className="absolute left-[3%] top-[54%] rounded-lg border border-[#5177a4]/30 bg-[#101f36]/80 px-3 py-2 text-[10px] uppercase tracking-[.18em] text-[#92b2d6] backdrop-blur-md">signal / 01</div>
    <div className="absolute bottom-[9%] left-[23%] rounded-lg border border-[#5177a4]/30 bg-[#101f36]/80 px-3 py-2 text-[10px] uppercase tracking-[.18em] text-[#92b2d6] backdrop-blur-md">scale / ∞</div>
    <div className="absolute right-[1%] top-[53%] rounded-lg border border-[#5177a4]/30 bg-[#101f36]/80 px-3 py-2 text-[10px] uppercase tracking-[.18em] text-[#92b2d6] backdrop-blur-md">trust / 100</div>
  </div>;
}

function SectionHeading({ eyebrow, title, body, light = false }: { eyebrow: string; title: string; body?: string; light?: boolean }) {
  return <div className="max-w-3xl">
    <div className="eyebrow mb-5">{eyebrow}</div>
    <h2 className={`font-display text-4xl font-medium leading-[1.08] tracking-[-.055em] sm:text-5xl lg:text-6xl ${light ? 'text-[#071226]' : 'text-[#e9f3ff]'}`}>{title}</h2>
    {body && <p className={`mt-6 max-w-2xl text-base leading-7 ${light ? 'text-[#526985]' : 'text-[#91a5bd]'}`}>{body}</p>}
  </div>;
}

function ContactForm({ services }: { services: string[] }) {
  const createRequest = useCreateContactRequest();
  const [sent, setSent] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', email: '', company: '', service: services[0] ?? 'AI strategy & portfolio', message: '' });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => {
    event.preventDefault(); setError('');
    if (!form.name || !form.email || !form.message) { setError('Please add your name, email, and a little about the opportunity.'); return; }
    createRequest.mutate({ data: form }, { onSuccess: () => setSent(true), onError: () => setError('We could not send that through. Please try again or email hello@addmatix.ai.') });
  };
  if (sent) return <div className="glass flex min-h-[390px] flex-col items-center justify-center rounded-2xl p-8 text-center"><div className="mb-6 grid h-14 w-14 place-items-center rounded-full bg-[#4286f5]/15 text-[#8bc5ff]"><Check /></div><h3 className="font-display text-2xl text-[#e8f3ff]">Signal received.</h3><p className="mt-3 max-w-sm text-sm leading-6 text-[#91a5bd]">A member of the AddMatix team will be in touch shortly. We look forward to hearing what you are building.</p><button onClick={() => { setSent(false); setForm({ name: '', email: '', company: '', service: services[0] ?? '', message: '' }); }} data-testid="button-send-another" className="mt-7 text-sm text-[#82baff] underline underline-offset-4">Send another message</button></div>;
  return <form onSubmit={submit} className="glass rounded-2xl p-5 sm:p-8">
    <div className="grid gap-5 sm:grid-cols-2">
      {([['name', 'Name', 'Your name'], ['email', 'Work email', 'you@company.com'], ['company', 'Company', 'Organisation']] as const).map(([key, label, placeholder]) => <label key={key} className={key === 'company' ? 'sm:col-span-1' : ''}><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#8aa2c1]">{label}</span><input data-testid={`input-contact-${key}`} type={key === 'email' ? 'email' : 'text'} value={form[key]} onChange={(e) => update(key, e.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-[#415a7d]/60 bg-[#0b172b]/75 px-4 py-3 text-sm text-[#e7f2ff] outline-none transition-colors placeholder:text-[#617793] focus:border-[#6baeff]" /></label>)}
      <label><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#8aa2c1]">What can we help with?</span><select data-testid="select-contact-service" value={form.service} onChange={(e) => update('service', e.target.value)} className="w-full appearance-none rounded-lg border border-[#415a7d]/60 bg-[#0b172b]/75 px-4 py-3 text-sm text-[#e7f2ff] outline-none focus:border-[#6baeff]">{services.map((service) => <option key={service}>{service}</option>)}</select></label>
      <label className="sm:col-span-2"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#8aa2c1]">A little context</span><textarea data-testid="textarea-contact-message" rows={4} value={form.message} onChange={(e) => update('message', e.target.value)} placeholder="What are you trying to make possible?" className="w-full resize-none rounded-lg border border-[#415a7d]/60 bg-[#0b172b]/75 px-4 py-3 text-sm leading-6 text-[#e7f2ff] outline-none transition-colors placeholder:text-[#617793] focus:border-[#6baeff]" /></label>
    </div>
    {error && <p data-testid="status-contact-error" className="mt-4 text-sm text-[#ff9da8]">{error}</p>}
    <div className="mt-6 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><p className="max-w-xs text-xs leading-5 text-[#7188a5]">We treat every conversation as confidential.</p><button disabled={createRequest.isPending} data-testid="button-submit-contact" className="group inline-flex items-center gap-3 rounded-full bg-[#4286f5] px-5 py-3 text-sm font-semibold text-[#071226] transition-all hover:bg-[#83bdff] disabled:cursor-wait disabled:opacity-60">{createRequest.isPending ? 'Sending…' : 'Send enquiry'}<Send className="h-4 w-4 transition-transform group-hover:translate-x-1" /></button></div>
  </form>;
}

export default function Home() {
  const query = useGetSiteContent({ query: { queryKey: getGetSiteContentQueryKey() } });
  const content = query.data ?? fallbackContent;
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activeCase, setActiveCase] = useState(0);
  const services = useMemo(() => content.services.map((service) => service.title), [content.services]);
  if (query.isLoading && !query.data) return <SiteSkeleton />;
  return <div className="hxa-noise min-h-[100dvh] overflow-hidden bg-[#08101f] text-[#e9f3ff]">
    <PublicNav />
    <main>
      <section className="relative isolate min-h-[760px] overflow-hidden border-b border-[#42618a]/15">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_42%,rgba(42,104,214,.19),transparent_30%),radial-gradient(circle_at_15%_90%,rgba(35,74,139,.14),transparent_36%)]" />
        <div className="absolute -right-32 top-24 h-96 w-96 rounded-full bg-[#2970df]/10 blur-3xl" />
        <div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-10 px-6 pb-16 pt-32 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-20 lg:pt-24">
          <div className="animate-rise">
            <div className="eyebrow mb-7">{content.hero.eyebrow}</div>
            <h1 data-testid="text-hero-headline" className="max-w-3xl font-display text-[3.45rem] font-medium leading-[.99] tracking-[-.075em] text-[#edf6ff] sm:text-7xl lg:text-[6.7rem]">{content.hero.headline}</h1>
            <p data-testid="text-hero-subheadline" className="mt-8 max-w-xl text-base leading-7 text-[#9aacc2] sm:text-lg">{content.hero.subheadline}</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><a href="#contact" data-testid="button-hero-primary" className="group inline-flex items-center gap-3 rounded-full bg-[#4286f5] px-5 py-3.5 text-sm font-semibold text-[#071226] transition-all hover:-translate-y-0.5 hover:bg-[#83bdff]">{content.hero.primaryCta}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></a><a href="#work" data-testid="button-hero-secondary" className="inline-flex items-center gap-2 rounded-full border border-[#607da5]/45 px-5 py-3.5 text-sm text-[#c6d8ec] transition-colors hover:border-[#8bbdff]">{content.hero.secondaryCta}</a></div>
            <div className="mt-14 flex items-center gap-4 text-xs text-[#7188a5]"><span className="h-px w-12 bg-[#5d86bb]" />Built for the moment when pilots become priorities</div>
          </div>
          <div className="animate-drift"><OrbitalVisual /></div>
        </div>
        <a href="#approach" data-testid="link-scroll-approach" className="absolute bottom-8 left-1/2 hidden -translate-x-1/2 items-center gap-2 text-[10px] uppercase tracking-[.18em] text-[#7086a1] sm:flex">Scroll to explore <ArrowDown className="h-3.5 w-3.5" /></a>
      </section>

      <section id="approach" className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-36"><div className="grid gap-14 lg:grid-cols-[.82fr_1.18fr]"><SectionHeading eyebrow="A different kind of partner" title="The distance between possibility and performance is where we work." /><div><p data-testid="text-intro" className="max-w-2xl text-2xl leading-[1.35] tracking-[-.03em] text-[#c8d7e9] sm:text-3xl">{content.intro}</p><div className="mt-10 flex items-center gap-3 text-sm text-[#75b2ff]"><span className="grid h-8 w-8 place-items-center rounded-full border border-[#568dce]/50"><MoveUpRight className="h-4 w-4" /></span>We make the complex legible.</div></div></div></section>

      <section className="border-y border-[#42618a]/15 bg-[#0d192b]/70"><div className="mx-auto grid max-w-7xl grid-cols-2 lg:grid-cols-4">{content.stats.map((stat, index) => <div key={stat.label} data-testid={`stat-${index}`} className={`border-[#42618a]/15 px-6 py-8 lg:px-8 lg:py-10 ${index < 2 ? 'border-r' : ''} ${index < 2 ? 'border-b lg:border-b-0' : ''} ${index === 2 ? 'border-r lg:border-r' : ''}`}><div className="font-display text-3xl tracking-[-.06em] text-[#e5f1ff] sm:text-4xl">{stat.value}</div><div className="mt-2 max-w-[150px] text-xs leading-5 text-[#8298b3]">{stat.label}</div></div>)}</div></section>

      <section id="capabilities" className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-36"><SectionHeading eyebrow="Our services" title="Build the system behind your next move." body="Explore the focused capabilities that take an idea from first signal to durable business advantage." /><div className="mt-16 grid items-start gap-4 lg:grid-cols-3">{content.services.map((service, index) => <article key={service.id} data-testid={`card-service-${service.id}`} className="group relative overflow-hidden rounded-2xl border border-[#456485]/35 bg-[#0d192b]/70 p-6 transition-all duration-500 hover:-translate-y-1 hover:border-[#6a9bd7]/65 hover:bg-[#12233d] sm:p-8"><a href={`/services/${service.id}`} data-testid={`button-service-${service.id}`} className="block cursor-pointer text-left"><div className="mb-20 flex items-start justify-between"><span className="font-mono text-xs text-[#6da7f7]">0{index + 1}</span><div className="flex items-center gap-3"><span className="text-[10px] uppercase tracking-[.12em] text-[#708caf]">View details</span><ArrowUpRight className="h-5 w-5 text-[#607d9f] transition-transform duration-300 group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#8cc4ff]" /></div></div><h3 className="font-display text-2xl tracking-[-.045em] text-[#e4f1ff]">{service.title}</h3><p className="mt-4 min-h-[72px] text-sm leading-6 text-[#8fa4bd]">{service.description}</p><div className="my-6 h-px bg-[#456485]/30" /><p className="text-sm leading-6 text-[#b7d0eb]">{service.outcome}</p><div className="mt-6 flex flex-wrap gap-2">{service.tags.map((tag) => <span key={tag} className="rounded-full border border-[#4f7199]/40 px-2.5 py-1 text-[10px] uppercase tracking-[.1em] text-[#7896b8]">{tag}</span>)}</div></a></article>)}</div></section>

      <section className="relative overflow-hidden bg-[#dcecff] px-6 py-24 text-[#081a36] lg:px-8 lg:py-32"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_80%_40%,rgba(66,134,245,.22),transparent_52%)]" /><div className="relative mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading light eyebrow="How change takes hold" title="A rhythm built for momentum." body="Transformation does not happen in a straight line. Ours is a deliberate loop: understand deeply, prove quickly, scale responsibly." /><div className="space-y-0">{content.process.map((step, index) => <div key={step} className="group flex items-center gap-5 border-t border-[#7798bd]/35 py-6 last:border-b"><span className="font-mono text-xs text-[#4286f5]">0{index + 1}</span><span className="font-display text-2xl tracking-[-.04em] transition-transform group-hover:translate-x-2 sm:text-3xl">{step}</span><ArrowRight className="ml-auto h-5 w-5 text-[#6f91ba] transition-transform group-hover:translate-x-2" /></div>)}</div></div></section>

      <section id="work" className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-36"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><SectionHeading eyebrow="Selected work" title="Proof, not promises." /><div className="flex gap-2">{content.caseStudies.map((item, index) => <button key={item.id} onClick={() => setActiveCase(index)} data-testid={`button-case-${item.id}`} className={`h-2 rounded-full transition-all ${activeCase === index ? 'w-9 bg-[#6fb1ff]' : 'w-2 bg-[#486688]'}`} aria-label={`Show case study ${index + 1}`} />)}</div></div><div className="mt-14 grid overflow-hidden rounded-2xl border border-[#4a6c96]/40 bg-[#0f1d33] lg:grid-cols-[1fr_.82fr]"><div className="relative min-h-[390px] overflow-hidden border-b border-[#4a6c96]/40 p-7 sm:p-10 lg:border-b-0 lg:border-r"><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(48,104,208,.13),transparent_55%),radial-gradient(circle_at_70%_25%,rgba(85,180,255,.18),transparent_22%)]" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><span className="eyebrow">{content.caseStudies[activeCase].industry}</span><span className="text-xs text-[#7793b4]">0{activeCase + 1} / 0{content.caseStudies.length}</span></div><div><div className="mb-5 flex h-16 w-16 items-center justify-center rounded-2xl border border-[#6eaeec]/40 bg-[#4286f5]/15"><Orbit className="h-7 w-7 text-[#9bcfff]" /></div><h3 className="max-w-lg font-display text-3xl leading-tight tracking-[-.05em] text-[#e7f3ff] sm:text-4xl">{content.caseStudies[activeCase].title}</h3><p className="mt-4 max-w-lg text-sm leading-6 text-[#91a7c2]">{content.caseStudies[activeCase].result}</p></div></div></div><div className="flex flex-col justify-between p-7 sm:p-10"><div><span className="text-xs uppercase tracking-[.16em] text-[#7692b3]">Client</span><div className="mt-3 font-display text-xl text-[#d9eaff]">{content.caseStudies[activeCase].client}</div></div><div className="mt-16"><span className="text-xs uppercase tracking-[.16em] text-[#7692b3]">Measured outcome</span><div data-testid="text-case-metric" className="mt-3 font-display text-3xl leading-tight tracking-[-.05em] text-[#76b7ff]">{content.caseStudies[activeCase].metric}</div></div><div data-testid="text-case-study-link" className="mt-12 inline-flex items-center gap-2 self-start text-sm text-[#a8caec]">Case study detail <ExternalLink className="h-4 w-4" /></div></div></div></section>

       <section className="border-y border-[#42618a]/15 bg-[#0b172a]"><div className="mx-auto grid max-w-7xl gap-14 px-6 py-24 lg:grid-cols-[.65fr_1.35fr] lg:px-8 lg:py-32"><div><div className="eyebrow">Why AddMatix</div><div className="mt-8 text-6xl font-display text-[#70b4ff]">∞</div><h2 className="mt-5 max-w-sm font-display text-3xl tracking-[-.05em] text-[#e6f2ff]">The confidence to move with care.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="glass rounded-2xl p-6"><ShieldCheck className="h-6 w-6 text-[#78b8ff]" /><h3 className="mt-12 font-display text-xl text-[#e4efff]">Practical by design</h3><p className="mt-3 text-sm leading-6 text-[#8da4bf]">The work has to survive contact with your teams, systems, and customers.</p></div><div className="glass rounded-2xl p-6"><Layers3 className="h-6 w-6 text-[#78b8ff]" /><h3 className="mt-12 font-display text-xl text-[#e4efff]">One connected view</h3><p className="mt-3 text-sm leading-6 text-[#8da4bf]">Strategy, technology, and adoption considered as one system — never separate workstreams.</p></div><div className="glass rounded-2xl p-6 sm:col-span-2"><Zap className="h-6 w-6 text-[#78b8ff]" /><h3 className="mt-12 font-display text-xl text-[#e4efff]">Built for your next chapter</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#8da4bf]">We build with your people, transfer the muscle, and leave the organisation stronger than we found it.</p></div></div></div></section>

       <section className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-36"><div className="grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="The AddMatix stack" title="Open by default. Intentional always." body="The best technology is the one that helps your teams make better decisions. We work across the modern data and intelligence ecosystem without locking you into a single answer." /><div className="flex flex-wrap content-start gap-3">{content.techStack.map((tech, index) => <div key={tech} data-testid={`tech-${index}`} className="group flex items-center gap-3 rounded-full border border-[#4d6d95]/45 bg-[#0d1b30] px-4 py-3 text-sm text-[#c4d8ee] transition-all hover:-translate-y-1 hover:border-[#72b5ff] hover:bg-[#142b4a]"><span className="h-2 w-2 rounded-full bg-[#4286f5] transition-shadow group-hover:shadow-[0_0_10px_3px_rgba(66,134,245,.7)]" />{tech}</div>)}</div></div></section>

      <section className="bg-[#dcecff] px-6 py-24 text-[#081a36] lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="eyebrow">From the room</div><div className="mt-8 h-px w-16 bg-[#4286f5]" /><p className="mt-7 font-display text-sm uppercase tracking-[.15em] text-[#6a82a0]">What partners say</p></div><div><blockquote data-testid="text-testimonial" className="font-display text-3xl leading-[1.18] tracking-[-.05em] sm:text-5xl">“{content.testimonials[0]?.quote}”</blockquote><div className="mt-10 flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#4286f5] font-display font-semibold text-[#071226]">{content.testimonials[0]?.name.split(' ').map((n) => n[0]).join('')}</div><div><div className="text-sm font-semibold">{content.testimonials[0]?.name}</div><div className="mt-1 text-xs text-[#617b9c]">{content.testimonials[0]?.role}, {content.testimonials[0]?.company}</div></div></div></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-36"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Questions, considered" title="Start with the useful ones." /><div className="border-t border-[#456487]/35">{content.faqs.map((faq, index) => <div key={faq.question} className="border-b border-[#456487]/35"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} data-testid={`button-faq-${index}`} className="flex w-full items-center justify-between gap-6 py-6 text-left"><span className="font-display text-lg tracking-[-.025em] text-[#d7e7f8]">{faq.question}</span><ChevronDown className={`h-5 w-5 shrink-0 text-[#76b7ff] transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button><div className={`grid transition-[grid-template-rows,opacity] duration-300 ${openFaq === index ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'}`}><p className="min-h-0 overflow-hidden pb-6 pr-12 text-sm leading-6 text-[#91a7c0]">{faq.answer}</p></div></div>)}</div></div></section>

      <section id="insights" className="border-t border-[#42618a]/15 bg-[#0d192b]/70"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-32"><div className="flex items-end justify-between gap-8"><SectionHeading eyebrow="Intelligence, shared" title="Notes for the next move." /><div data-testid="text-insights-index" className="hidden items-center gap-2 text-sm text-[#86bcfa] sm:flex">Latest thinking <ArrowRight className="h-4 w-4" /></div></div><div className="mt-14 grid gap-4 md:grid-cols-3">{content.posts.map((post) => <article key={post.id} data-testid={`card-post-${post.id}`} className="group rounded-2xl border border-[#456487]/35 p-6 transition-colors hover:border-[#6faef2]/65"><div className="flex items-center justify-between text-[10px] uppercase tracking-[.15em] text-[#7094ba]"><span>{post.category}</span><Clock3 className="h-3.5 w-3.5" /></div><h3 className="mt-16 font-display text-xl leading-snug tracking-[-.035em] text-[#dcecff] transition-colors group-hover:text-[#83c1ff]">{post.title}</h3><p className="mt-4 text-sm leading-6 text-[#869db8]">{post.excerpt}</p><div className="mt-8 flex items-center justify-between text-xs text-[#6d87a5]"><span>{post.readTime}</span><ArrowUpRight className="h-4 w-4 text-[#75b5fb]" /></div></article>)}</div></div></section>

      <section id="contact" className="mx-auto max-w-7xl px-6 py-24 lg:px-8 lg:py-36"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="eyebrow">Make the next move</div><h2 className="mt-6 max-w-md font-display text-5xl leading-[1.02] tracking-[-.065em] text-[#eaf4ff] sm:text-6xl">Have a signal worth following?</h2><p className="mt-6 max-w-sm text-base leading-7 text-[#90a5bf]">Tell us where you are headed. We will bring a point of view, not a pitch.</p><div className="mt-10 flex items-center gap-3 text-sm text-[#9eb5d0]"><Mail className="h-4 w-4 text-[#6eb0fc]" />hello@addmatix.ai</div></div><ContactForm services={services} /></div></section>
    </main>
    <footer className="border-t border-[#42618a]/15"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-6 py-8 sm:flex-row sm:items-center lg:px-8"><div><span className="font-display text-lg font-bold tracking-[-.06em]">ADX<span className="text-[#6eafff]">.</span></span><p className="mt-2 text-xs text-[#6f86a4]">Intelligence, made operational.</p></div><div className="flex items-center gap-6 text-xs text-[#7087a3]"><span>© {new Date().getFullYear()} AddMatix</span><a href="#contact" className="hover:text-[#b8d9fa]">Contact</a></div></div></footer>
  </div>;
}